# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-26 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20180626_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=' ', unique=True),
            preserve_default=False,
        ),
    ]
